/*cria uma base de dados no banco de dados*/
CREATE DATABASE PROJETO;

/*usando apenas o banco de dados que ira usar*/
USE PROJETO

/*CRIANDO TABELA CLIENTE*/
CREATE TABLE CLIENTES(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INTEGER (11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/*VISUALIZANDO AS TABELAS EXISTENTES NO BANCO DE DADOS*/
SHOW TABLES;

/*VISUALIZANDO A ESTRUTURA DE UMA TABELA-> VISUALIZAR CAMPOS TIPOS E DESCRCAO*/
DESC CLIENTES;

/*INSERINDO DADOS N TABELA CLIENTES*/
INSERT INTO CLIENTES(NOME,SEXO,EMAIL,CPF,TELEFONE,ENDERECO)
VALUES('BRENO','M','BRENO.MORAIS@GMAIL.COM',0703598817,'65992484229','BAIRRO');

/*INSERINDO DADOS N TABELA CLIENTES OMETINDO */
INSERT INTO CLIENTES VALUES('BRENO','M','BRENOMORAIS@GMAIL.COM',0703598817,'65992484229','BAIRRO');

/*CONSULTAR DADOS NA TABELAS*/
SELECT * FROM CLIENTES;




aula -> 2. 17 - Conhecendo as Projeções
